version:  "3"

services:
  mssql_admin:
    image: mcr.microsoft.com/azure-sql-edge:latest
    cap_add: [ 'SYS_PTRACE' ]
    environment:
      - "ACCEPT_EULA=1"
      - "MSSQL_SA_PASSWORD=SU2orange!"
    ports:
      - "3341:1433"
    hostname: mssql_admin
    volumes:
      - "mssql-azuresql-edge-data:/var/opt/mssql"

  bokiback:
    build: .
    environment:
      - "CONNECTION_STRING=Data Source=mssql_admin,1433;Initial Catalog=appointment;User Id=sa;Password=SU2orange!;Encrypt=False;TrustServerCertificate=True"   
    ports:
      - "9292:8080"    
    depends_on:
      - mssql_admin         
volumes:
    mssql-azuresql-edge-data: